[package]
name = "zydeco-driver"
version = { workspace = true }
rust-version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
# homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
description = "the source-file compiler pipeline for zydeco"

[dependencies]
zydeco-utils = { workspace = true }
zydeco-syntax = { workspace = true }
zydeco-surface = { workspace = true }
zydeco-statics = { workspace = true }
zydeco-dynamics = { workspace = true }
zydeco-amd64 = { workspace = true }
zydeco-llvm = { workspace = true }
zydeco-assembly = { workspace = true }
zydeco-stackir = { workspace = true }
derive_more = { workspace = true, features = ["display", "from"] }
thiserror = { workspace = true }
ariadne = { workspace = true }
sculptor = { workspace = true }
dashmap = { workspace = true }
salsa = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }

[lib]
doctest = false

[dev-dependencies]
tempfile = { workspace = true }
