[package]
name = "zydeco-runtime"
version = "0.0.0"
edition = "2024"
build = "build.rs"

[workspace]

[workspace.dependencies]
zydeco-machine = { path = "../lang/machine", features = ["runtime"] }
rand = "0.10"

[[bin]]
name = "main"
path = "stub.rs"

[dependencies]
zydeco-machine = { workspace = true }
rand = { workspace = true }
