name = "Zydeco"
grammar = "zydeco"
path_suffixes = ["zy", "zyi", "zydeco"]
line_comments = ["-- "]
block_comment = ["/-", "-/"]
tab_size = 2
word_characters = ["'", "?", "+", "*", "-", "=", "~", "#"]
autoclose_before = ")]}'\":;>"
brackets = [
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "{", end = "}", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]
