id = "zydeco"
name = "Zydeco"
description = "Zydeco language support powered by the Cajun language server"
version = "0.3.0"
schema_version = 1
authors = ["The Zydeco Project Developers"]
repository = "https://github.com/zydeco-lang/zydeco"

[language_servers.cajun]
languages = ["Zydeco"]
language_ids = { Zydeco = "zydeco" }

[grammars.zydeco]
repository = "https://github.com/zydeco-lang/zydeco"
rev = "53f956eb693e9244894c1afa92d5e11c57b711bc"
path = "editor/tree-sitter-zydeco"
