id = "zydeco"
name = "Zydeco"
description = "Zydeco language support powered by the Cajun language server"
version = "0.3.0"
schema_version = 1
authors = ["The Zydeco Project Developers"]
repository = "https://github.com/zydeco-lang/zydeco"

[language_servers.cajun]
languages = ["Zydeco"]
language_ids = { Zydeco = "zydeco" }

[grammars.zydeco]
repository = "https://github.com/zydeco-lang/zydeco"
rev = "996d04ca9e9b48dfb9f4822de7a923e90ec4d744"
path = "editor/tree-sitter-zydeco"
