id = "zydeco"
name = "Zydeco"
description = "Zydeco language support powered by the Cajun language server"
version = "0.3.0"
schema_version = 1
authors = ["The Zydeco Project Developers"]
repository = "https://github.com/zydeco-lang/zydeco"

[language_servers.cajun]
languages = ["Zydeco"]
language_ids = { Zydeco = "zydeco" }

[grammars.zydeco]
repository = "https://github.com/zydeco-lang/zydeco"
rev = "ec115ccb079ec61549719412b5390952f570c8a4"
path = "editor/tree-sitter-zydeco"
