[env]
RUST_MIN_STACK = "4194304"

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

[alias]
check-workspace = "check --workspace --exclude zydeco-runtime"
build-workspace = "build --workspace --exclude zydeco-runtime"
test-workspace = "test --workspace --exclude zydeco-runtime"
clippy-workspace = "clippy --workspace --exclude zydeco-runtime"
clippy-fix-workspace = "clippy --workspace --exclude zydeco-runtime --fix"
doc-workspace = "doc --workspace --exclude zydeco-runtime"
