[env]
RUST_MIN_STACK = "4194304"

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

[alias]
test-workspace-low = "test --workspace -- --test-threads=2"
check-workspace = "check --workspace"
build-workspace = "build --workspace"
test-workspace = "test --workspace"
clippy-workspace = "clippy --workspace"
clippy-fix-workspace = "clippy --workspace --fix"
doc-workspace = "doc --workspace"
