[package]
name = "zydeco-tests"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
zydeco-session = { workspace = true }
zydeco-statics = { workspace = true }
zydeco-cli = { path = "../../cli" }
zydeco-stackir = { workspace = true }
thiserror = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
