[package]
name = "zydeco-tests"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
zydeco-machine = { workspace = true }
zydeco-session = { workspace = true }
zydeco-statics = { workspace = true }
zydeco-cli = { workspace = true }
zydeco-stackir = { workspace = true }
thiserror = { workspace = true }
tempfile = { workspace = true }
walkdir = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
libtest-mimic = { workspace = true }
zydeco-assembly = { workspace = true }

[[test]]
name = "cases"
harness = false
