[package]
name = "zydeco-wasm-common"
version = { workspace = true }
rust-version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
description = "Shared WebAssembly backend support for Zydeco"

[dependencies]
zydeco-syntax = { workspace = true }
thiserror = { workspace = true }
wasm-encoder = { workspace = true }

[lints]
workspace = true
