name: Release

on:
  push:
    tags: [ "v*" ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Generate release notes
      uses: orhun/git-cliff-action@v4
      id: cliff
      with:
        config: cliff.toml
        args: --latest --strip header
      env:
        OUTPUT: RELEASE_NOTES.md
        GITHUB_REPO: ${{ github.repository }}
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        body: ${{ steps.cliff.outputs.content }}
